version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api-gateway:
    build: ./api-gateway
    networks:
      - my_network
    ports:
      - "3000:3000"
    depends_on:
      - redis

  user-registration-service:
    build: ./user-registration-service-manager
    networks:
      - my_network
    ports:
      - "5000:5000"
    command: python create_new_user_rest_api.py
    depends_on:
      - redis

  celery-worker-principal:
    build: ./user-registration-service-manager
    command: celery -A user_registration_service_principal worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  celery-worker-redundancia1:
    build: ./user-registration-service-manager
    command: celery -A user_registration_service_redundancia1 worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  celery-worker-redundancia2:
    build: ./user-registration-service-manager
    command: celery -A user_registration_service_redundancia2 worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  celery-worker-ping:
    build: ./user-registration-service-manager
    command: celery -A ping_service_log worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  celery-worker-failures:
    build: ./user-registration-service-manager
    command: celery -A failures_with_user_registration_log worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

networks:
  my_network:
    driver: bridge